// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU7mB6X_Ll8hpAy_KSrQlOro2vHXQYvs8',
    appId: '1:64809963800:web:86b9b47392746bd1bc4e6d',
    messagingSenderId: '64809963800',
    projectId: 'inexture-1',
    authDomain: 'inexture-1.firebaseapp.com',
    storageBucket: 'inexture-1.firebasestorage.app',
    measurementId: 'G-9LC55FKJQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAArwAOQPMZVvz7YZlDhcf-IUDFptjP_Jk',
    appId: '1:64809963800:android:f6b8a1c561814e33bc4e6d',
    messagingSenderId: '64809963800',
    projectId: 'inexture-1',
    storageBucket: 'inexture-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbI2kvRJ-N-AqSZqBvvNQ9AJPu9dWW_CE',
    appId: '1:64809963800:ios:5428e64c68c23ff5bc4e6d',
    messagingSenderId: '64809963800',
    projectId: 'inexture-1',
    storageBucket: 'inexture-1.firebasestorage.app',
    iosBundleId: 'com.inexture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-qKd7SlpgAMs64itVyI2x72muRWmzdpE',
    appId: '1:64809963800:ios:e0dacc95c370ececbc4e6d',
    messagingSenderId: '64809963800',
    projectId: 'inexture-1',
    storageBucket: 'inexture-1.firebasestorage.app',
    iosBundleId: 'com.example.inexturePortalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs9w9YjClQrr1i-zIgRqEF-NWblriuERM',
    appId: '1:64809963800:web:b18a81d82113e5f7bc4e6d',
    messagingSenderId: '64809963800',
    projectId: 'inexture-1',
    authDomain: 'inexture-1.firebaseapp.com',
    storageBucket: 'inexture-1.firebasestorage.app',
    measurementId: 'G-PCQE3ZKNBF',
  );
}
