name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Flutter with specific version
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.30.0-1.0.pre.426'
          channel: master

      # Enable flutter commands
      - name: Flutter Doctor
        run: flutter doctor -v

      # Get dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run analysis (only on lib/ and test/ to avoid noise)
      - name: Analyze Code
        run: flutter analyze lib test

      # Run unit tests
      - name: Run Tests
        run: flutter test
