name: Flutter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flutter-ci:
    name: Flutter Analyze, Test, and Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Flutter (>=3.22.0 includes Dart >= 3.5.2)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'  # ✅ Change to exact or latest if needed

      # Step 3: Disable analytics (optional, but avoids first-run output)
      - name: Disable analytics
        run: flutter config --no-analytics --no-cli-animations

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Analyze Dart code
      - name: Analyze code
        run: flutter analyze

      # Step 6: Run unit/widget tests
      - name: Run tests
        run: flutter test

      # Step 7: Build debug APK
      - name: Build APK
        run: flutter build apk --debug

      # Step 8: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
