name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Flutter from master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: 'master' # temporary base version

      - name: Checkout exact Flutter version
        run: |
          cd $FLUTTER_ROOT
          git fetch --tags
          git checkout 842db35d27
          flutter doctor
          flutter --version

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
