    name: Flutter CI

    on:
      push:
        branches:
          - main

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - uses: subosito/flutter-action@v2 # Use a specific version, e.g., v2
          with:
            flutter-version: '3.22.2' # Specify the desired Flutter version

        - run: flutter pub get
        - run: flutter test
        - run: flutter build apk --release # Example build command
