name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: '3.30.0'  # nearest supported version

      - name: Checkout exact Flutter version tag/commit
        run: |
          cd $FLUTTER_ROOT
          git fetch --tags
          git checkout 842db35d27  # exact version you need
          flutter --version

      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release
