name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter (dev channel)
        uses: subosito/flutter-action@v2
        with:
          channel: dev
          flutter-version: '3.23.0-0.1.pre'
          cache: true

      - name: Show Flutter + Dart version
        run: flutter --version

      - name: Disable analytics (optional)
        run: flutter config --no-analytics --no-cli-animations

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
