name: Flutter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flutter-ci:
    name: Flutter Analyze, Test, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # ⬇️ Manually install Flutter from master channel
      - name: Clone Flutter from master branch
        run: |
          git clone https://github.com/flutter/flutter.git -b master
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Disable Flutter analytics
        run: flutter config --no-analytics --no-cli-animations

      - name: Enable master channel (just in case)
        run: flutter channel master

      - name: Upgrade Flutter to latest master version
        run: flutter upgrade

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze Dart code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
